name: Deploy DeamV Web to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Setup Node.js Environment
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      # 2. Inject Environment Variables from GitHub Secrets
      - name: Inject Environment Variables for Build
        run: echo "Secrets will be injected into the build environment."
        env:
          # Inject all environment variables here using the secrets
          NEXT_PUBLIC_GRADED_QUIZ_ENABLED: ${{ secrets.NEXT_PUBLIC_GRADED_QUIZ_ENABLED }}
          NEXT_PUBLIC_QUIZ_NUMBER: ${{ secrets.NEXT_PUBLIC_QUIZ_NUMBER }}
          NEXT_PUBLIC_QUIZ_TIME_LIMIT: ${{ secrets.NEXT_PUBLIC_QUIZ_TIME_LIMIT }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          GOOGLE_PRACTICE_SHEET_ID: ${{ secrets.GOOGLE_PRACTICE_SHEET_ID }}
          GOOGLE_TEST_SHEET_ID: ${{ secrets.GOOGLE_TEST_SHEET_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      # 3. Build Next.js Application
      - name: Install dependencies and build Next.js app
        run: |
          npm install --force
          npm run build
          
          echo "Starting artifact packaging..."
          mkdir -p build_archive_temp
          
          # 2. Use rsync to copy ONLY necessary files
          rsync -av \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'nextjs_build.tar.gz' \
            ./ build_archive_temp/
          
          # 3. Create a compressed archive
          tar -czf nextjs_build.tar.gz -C build_archive_temp .
          
          # 4. Clean up
          rm -rf build_archive_temp
        
      # 4. Verify files exist locally before copying
      - name: Verify deployment file locally
        run: |
          echo "Checking local deployment file:"
          ls -la nextjs_build.tar.gz || { echo "ERROR: nextjs_build.tar.gz missing"; exit 1; }
          echo "File size:"
          du -h nextjs_build.tar.gz

      # 5. Copy files to server
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "nextjs_build.tar.gz"
          target: "~/deployments"
          rm: true 

      # 6. SSH into server & deploy
      - name: SSH into server & deploy with backup rotation
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            echo "Starting Next.js deployment process..."
            
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            BASE_DIR="/var/www/deamv-web" 
            DEPLOY_DIR="$HOME/deployments"
            
            # --- Utility Function ---
            rotate_backups() {
              local DIR=$1
              if [ -d "$DIR" ]; then
                echo "Creating backup of $DIR"
                tar -czf "${DIR}_backup_$TIMESTAMP.tar.gz" --exclude=node_modules "$DIR"
                ls -dt ${DIR}_backup_*.tar.gz 2>/dev/null | tail -n +4 | xargs -r rm -f
              else
                echo "Directory $DIR does not exist, no backup needed"
              fi
            }

            # 6a. Verify deployment file
            echo "Checking for deployment file in $DEPLOY_DIR..."
            if [ ! -f "$DEPLOY_DIR/nextjs_build.tar.gz" ]; then
              echo "ERROR: nextjs_build.tar.gz not found!"
              exit 1
            fi

            # 6b. Deploy Next.js
            echo "Deploying Next.js application..."
            rotate_backups "${BASE_DIR}/current"
            
            TEMP_DIR="/tmp/nextjs_extract_$TIMESTAMP"
            mkdir -p "$TEMP_DIR"
            
            # Extract to a temp directory
            tar -xzf "$DEPLOY_DIR/nextjs_build.tar.gz" -C "$TEMP_DIR"
            
            # Remove old 'current' directory and replace with new build
            rm -rf "${BASE_DIR}/current"
            mv "${TEMP_DIR}" "${BASE_DIR}/current"
            
            # 6c. Install Production Dependencies
            echo "Installing production dependencies..."
            cd "${BASE_DIR}/current"
            npm install --production --prefer-offline 
            npm install --save-dev typescript
            
            # 6d. Restart Next.js Service
            echo "Restarting Next.js service..."
            sudo systemctl daemon-reload
            sudo systemctl restart deamv || echo "Warning: Could not restart Next.js service. Check systemctl."

            # 6e. Cleanup
            echo "Cleaning up deployment files..."
            rm -rf "$DEPLOY_DIR/nextjs_build.tar.gz"
            
            echo "Deployment completed successfully! Next.js application is live."
